### ISSUE TITLE
Improve GUI readibility (font size, proper UI scaling for high resolutions)

### ISSUE THREAD

**Issue by G-i-o** [dawidm/cryptonose2#1]
Hello,

Thank You for making and maitaining Cryptonose.

ATM, I find it difficult to read the Cryptonose screen due to the bright white light and the small characters used.

I'd suggest a dark mode and bigger characters.

Thanks.

**Comment by dawidm** [comment]
Hello,

Thank you very much for the feedback.

The problem with font size could be due to the lack of UI scaling for higher resolutions. What's your OS and screen resolution? The UI isn't scaled properly on my Linux Mint with XFCE and as far as I know it's generally a problem on Linux. I'll work on adding font size setting - this should help in most cases.

Dark mode is definitely good idea, I will add it as a separate issue and see what I can do.

**Comment by dawidm** [comment]
Dark theme issue: https://github.com/dawidm/cryptonose2/issues/2

**Comment by G-i-o** [comment]
Hi @dawidm 

Hi Dawid,

Thank You for responding to this so promptly.

The OS in question is Linux Manjaro XFCE with a 1920*1080 resolution.

Yes, font size setting and dark mode would be fantastic. Thank YOU very much.

Much appreciated.
:pray:

**Comment by dawidm** [comment]
I've added option to change font size. It will be available in the next release.

About scaling for hidpi. Interface is scaling well for Windows and Linux. For Linux GDK_SCALE environment variable can be used to modify the scaling factor, but as far as I know, only integer values work.
There's problem with notifications - they could be small on very high dpi screens, but no fix for this so far.
