### ISSUE TITLE
Damaged dmg file

### ISSUE THREAD

**Issue by 1mehdifaraji** [dawidm/cryptonose2#10]
I've downloaded the dmg file and moved it to applications on my macbook pro m1 but I get this error trying to open application :
<img width="281" alt="Screen Shot 1401-05-12 at 22 55 14" src="https://user-images.githubusercontent.com/63982703/182681985-c9e4224e-1d7e-4c35-9fa8-da851c0a8d50.png">

**Comment by dawidm** [comment]
Unfortunately I don't have much experience with mac os. I'm testing mainly on Linux and Windows. However I've tested it couple times on mac and it always worked without problems. The problem with dmg file is probably not because of damaged file, but security issues - your system treats the file as unsafe because it's downloaded from other source than official app store. You could try to use pkg file with instructions provided on the cryptonose page https://dawidm.github.io/cryptonose2/download/ 
Please let me know whether it helps.
