### ISSUE TITLE
[REQUEST] Add support for the biggest DEX services

### ISSUE THREAD

**Issue by AffeN01** [dawidm/cryptonose2#7]
It would be great if there was Uniswap/1inch/Sudhiswap (etc.) support, because it would provide valuble info about smaller tokens, while reinforcing the spirit of decentralization and FLOSS.

**Comment by dawidm** [comment]
I also think it would be useful, but not sure if possible to implement for now. The problem is getting frequent price updates from the DEX, which I cannot do without suitable public API (which is not common for DEX). I will keep this issue open and if I get to know a way to implement support for any DEX, I'll try.

**Comment by dawidm** [comment]
Update: I'm currently experimenting with implementation of Uniswap V3 using The Graph API.

**Comment by dawidm** [comment]
Uniswap V3 is added in the next release, others may be added in the future if possible.
